- name: install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: start and enable the service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Remove old files
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent
    
- name: Create a directory 
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download file from a file path
  ansible.builtin.get_url:
    url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    dest: /tmp/frontend.zip
    
- name: unzip file
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Connecting to nginx
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf