- name: install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: start and enable the service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true