- name: remove the old folder/directory
  ansible.builtin.file:
    path: "{{ app_loc }}"
    state: absent

- name: create directory
  ansible.builtin.file:
    path: "{{ app_loc }}"
    state: directory

- name: download code
  ansible.builtin.unarchive:
    src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component }}-v2.zip"
    dest: "{{ app_loc }}"
    remote_src: yes