- name: disable node js
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable node js
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install node js
  ansible.builtin.command: dnf install nodejs -y

- name: Add the user
  ansible.builtin.user:
    name: expense
    state: present

- name: Create a app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download file from a file path
  ansible.builtin.get_url:
    url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
    dest: /tmp/backend.
    
- name: unzip the file
  ansible.builtin.unarchive:
    src: /tmp/backend.zip
    dest: /app
    remote_src: yes

