- name: disable node js
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable node js
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install node js
  ansible.builtin.command: dnf install nodejs -y

- name: Add the user
  ansible.builtin.user:
    name: expense
    state: present
