- name: disable node js
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable node js
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install node js
  ansible.builtin.command: dnf install nodejs -y

- name: install python modules
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
    - PyMySQL
    - cryptography

- name: install mysql
  ansible.builtin.package:
    name: mysql
    state: present

- name: Add the user
  ansible.builtin.user:
    name: expense
    state: present

- name: common roles
  include_role:
    name: common
    tasks_from: main


# - name: Create a app directory
#   ansible.builtin.file:
#     path: /app
#     state: directory

# - name: Download file from a file path
#   ansible.builtin.get_url:
#     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
#     dest: /tmp/backend.zip
    
# - name: unzip the file
#   ansible.builtin.unarchive:
#     src: /tmp/backend.zip
#     dest: /app
#     remote_src: yes

- name: Install packages
  community.general.npm:
    path: /app

- name: setup backend services
  ansible.builtin.template:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: import mysql data
  community.mysql.mysql_db:
    state: import
    name: all
    login_user: root
    login_password: "{{ a_pwd }}"
    login_host: mysql.katta.blog
    target: /app/schema/backend.sql

- name: Restart service 
  ansible.builtin.systemd_service:
    name: backend
    state: restarted
    daemon_reload: true
    enabled: true


